### ISSUE TITLE
Hitta på ett bättre arbetsnamn

### ISSUE THREAD

**Issue by ovidner** [litheblas/blasfisk#38]
Varje projekt med självaktning har ju ett coolt arbetsnamn och "litheblas" är skittråkigt. Jag föreslår att vi hittar på något bra och byter namespace och namn på repot innan en sådan ändring skulle ställa till med för mycket oreda.

**Comment by ovidner** [comment]
Blåsfisk!

**Comment by ovidner** [comment]
Oops, trodde man kunde ha flera assignees... Det gick visst inte, men nu har ni fått en nys om det!

**Comment by ovidner** [comment]
Jag tog mig friheten att sätta detta i verket pga. inga protester. Alla gamla sökvägar ska dock fungera som tidigare, så förhoppningsvis ställer det inte till för mycket. Kanske.

**Comment by Karlinde** [comment]
Oh, missade helt det mailet att issuet hade skapats. Ohwell, blasfisk funkar fint ;)

**Comment by ovidner** [comment]
Jag får ju medge att jag tycker det också är ett jättefånigt namn, men men... Det är skojigare/oklarare än litheblas i alla fall.
