### ISSUE TITLE
Lägg till travis-ci junket

### ISSUE THREAD

**Issue by GustavHager** [litheblas/blasfisk#5]
för automatiska UNITTESTS!!

**Comment by talkmill** [comment]
Tänker vi oss den hostade travis-ci då eller vill vi ha något som rullar på egna servrar? (kanske underlättar build-hooks då?

**Comment by talkmill** [comment]
Har kollat lite med. Något som vore snyggt är att köra all testning i hostad travis-ci och sedan lägga in deployment-hook via egen django-app. Det skulle göra att:
1. Vid pull requests skulle travis-ci hoppa in, skapa en virtuell server där den testmergear din branch och development(master) och sedan installerar applikationen och kör alla enhestest för att sedan visa en grön ruta i github om det gick bra och lite loggning etc.
2. Ha en Django-app som lyssnar på webhook ifrån github som deployar om allt om github säger att något nytt deployats till master

**Comment by talkmill** [comment]
Var inte meningen att stänga ;)

**Comment by talkmill** [comment]
travis-ci är konfat och kan ses på https://travis-ci.org/Litheblas/litheblas/builds
