### ISSUE TITLE
Hitta bilder till startsidan

### ISSUE THREAD

**Issue by ovidner** [litheblas/blasfisk#50]
Det behövs bilder till startsidan som uppfyller ungefär följande egenskaper:
- Hyfsat normala höjd-bredd-proportioner.
- Minst 1600 pixlar på bredden, gärna fler. (För att se riktigt bra ut även på t.ex. en Retinaskärm)
- Det roliga/viktiga/centrala i bilden måste ligga ungefär i de _mittersta två femtedelarna_ av bildens höjd. (För att just det centrala inte ska skäras bort)
- Bilden måste färgmässigt fungera tillsammans med off-yellow. Det här kan vi kanske fixa själva om vi får i övrigt bra original.

**Comment by ovidner** [comment]
@Pernilladwl pratade om att fixa det här förut. Jag sätter dig som assignee.

**Comment by cr3ation** [comment]
Bilder till startsidan är fixade. Stänger ärendet.
